### ISSUE TITLE
Figures format mismatch

### ISSUE THREAD

**Issue by Sunt-ing** [elianap/divexplorer_SIGMOD21_experiments#5]
I think there are some mismatchs between the paper and my local output. I list them here. Should be just format issues and easy to fix.

![图片](https://user-images.githubusercontent.com/43040147/149917775-d39745db-d1ea-4c9b-b445-ff921dc79f50.png)
![图片](https://user-images.githubusercontent.com/43040147/149918126-92069b37-0dce-4220-93ac-840fed65cbde.png)
![图片](https://user-images.githubusercontent.com/43040147/149918204-a7ec13bc-b86a-4259-84cc-c89ff9d8887f.png)
![图片](https://user-images.githubusercontent.com/43040147/149918303-49902bc9-ee27-43a5-ac69-92fd0ef6c3a3.png)
![图片](https://user-images.githubusercontent.com/43040147/149918440-802764bc-72ca-4865-9a07-383b10474a54.png)

**Comment by Sunt-ing** [comment]
Hope that they can be fixed soon. Thanks!

**Comment by Sunt-ing** [comment]
I found you fixed figure 8 and figure 9, thanks! How about other figures? @elianap

**Comment by elianap** [comment]
Hi! Figure 3 was fixed with commit a519b93aaa79dac54a840db53f7048500cdb8c7e on 25 Dec. The legend mismatch in Figure 7 was fixed in 05a9a8328068fcdd1e117921c02f20db15ed2ee4 (I wrote the wrong id of the figure in the commit..). While Figure 8 and 9, as you mention, in 2b1672422a8db8ab7139a46d51f1b5e4437290de. 
The format of Figure 11 is still to be fixed. I will do in the day, the next up most. Is it okay or there is a deadline?

**Comment by Sunt-ing** [comment]
Hello. I do have a deadline: Tomorrow (in the Beijing time zone). 
I pulled your code and ran the experiment again, and luckily found that figure 7 and figure 8 had been fixed. But:
- Figure 3 is not fixed because figure 3 in the paper have only one chart, while figure 3 in my output has two (also a little different).
![图片](https://user-images.githubusercontent.com/43040147/150102242-b4ea1a80-930a-4219-8c08-5a14c567848b.png)
- Figure 9 is not fixed because the lengths of the two bars are different. 
![图片](https://user-images.githubusercontent.com/43040147/150102098-7cf3780a-6600-4587-ac5f-5a2bff252ac6.png)
- And yes, figure 11 is still to be fixed.

**Comment by elianap** [comment]
Thank you for letting me know!

Figure 3
I slightly change the function to plot figure_3 in commit f5b9d8990afa34ea99ae145518cfcdb14cc421b7.
By running python E01_compas.py --no_show_figs (--no_show_figs is just to save the figure visualizing them while running) I obtain the figures related to the compas results. I have uploaded figure_3 in commit f460d60b9785a7f8dbe6ef86b2f9e95c4fc71022. Can you not reproduce it? An important change was the commit a519b93aaa79dac54a840db53f7048500cdb8c7e.

For Figure 9

By running python E02_adult.py --no_show_figs  I obtain the figures and tables related to the adult dataset. 
As default, E02 (and run_experiment scripts) with use_processed=True that corresponds to the retrain parameter (it was already configure as False and I set to False in commit 2b1672422a8db8ab7139a46d51f1b5e4437290de.   
If we do not specify --retrain, the approach evaluated the FPR/FNR with the exact same predicted labels as in the paper (I have uploaded the predicted labels in the repo for reproducibility reasons). Our approach will use the predicted label to derive the global behavior reported in Figure 9. Our goal is in fact to study the model behavior.
If we set --retrain, the model is retrained. Since it is retrained, for slightly changes of the model randomicity (as the version of libraries), we may have a slightly change of the model, therefore of the prediction and consequently also of the explanations of the behavior in Figure 9 (since it is a slightly different model).
I have uploaded the figure_9 I obtain by running python E02_adult.py --no_show_figs in commit f460d60b9785a7f8dbe6ef86b2f9e95c4fc71022. Is it reproducible with the current version of the code (with all commits)? 

For Figure 11

Thank your for letting me know of the deadline. We slightly change during the camera ready the code just for visualization purposes (we changed the color for readability reasons and we abbreviate the labels). I will fix the code for matching the visualization!

**Comment by elianap** [comment]
I fixed the colors and abbreviations of Figure_11

**Comment by Sunt-ing** [comment]
I retried, and was happy to found that
- got exact Figure_3
- my local Figure_11 had the same topology as the paper's. 

However, the Figure_9 cannot be reproduced and my outputted figure was always the same:
![图片](https://user-images.githubusercontent.com/43040147/150135577-bbd9ef0c-21da-4033-bfbb-fffd41764189.png)

**Comment by elianap** [comment]
I committed a new version in which I force the use of the pre-computed labels as in the paper. I also tried to create a new environment from scratch (in two different OS) and the result is as the one I uploaded. 
Can you try with the committed version? You can directly test figure 9 with:
python E02_adult.py --compute_results figure_9 --no_show_figs
Thank you for your work!

**Comment by Sunt-ing** [comment]
Sadly, but nothing change.

**Comment by Sunt-ing** [comment]
My environments:
![图片](https://user-images.githubusercontent.com/43040147/150152224-e9ac0742-42f6-4a13-9709-3afd19493659.png)

**Comment by elianap** [comment]
Thank you for your availability. 
I added a folder "dict_reproducibility" where I stored the results of the two plotted dictionaries (both and after the normalization). 
In the new committed version, by running "E02_adult.py --compute_results figure_9 --no_show_figs" you will also store in ./output/dict your dictionary results. In this way, you can compare also quantitatively the results. I store the results also to be sure it was not a visualization problem.
I tried on a 3rd environment (a Linux server), cloning the current (and last status) of the repository and creating again the environment from scratch. The obtained dictionary (in the dict folder) matches (as the figure) with the results I stored in "dict_reproducibility". I again ran python E02_adult.py --compute_results figure_9 --no_show_figs.

**Comment by Sunt-ing** [comment]
output\dict\global_shapley_positive_fpr_top_normalized.json
```json
{
	"sex=M": 0.2985398575031534,
	"status=Married": 1.0,
	"relation=Husband": 0.5547055582683241,
	"age=>47": 0.22479404730492833,
	"age=(37-47]": 0.24912190118441713,
	"hoursXW=>45": 0.6636943095775011,
	"edu=Bachelors": 0.3166016264691137,
	"occup=Prof": 0.22671465596359197,
	"occup=White-Collar": 0.25210816494278526,
	"hoursXW=(40-45]": 0.24620489262309653,
	"workcl=Local-gov": 0.14040049578460612,
	"edu=Masters": 0.31043708192908887
}
```

output\dict_reproducibility\global_shapley_positive_fpr_top_normalized.json
```json
{
	"sex=M": 0.3657915667041926,
	"status=Married": 1.0,
	"relation=Husband": 0.7138952883018846,
	"age=>47": 0.2549593777501226,
	"age=(37-47]": 0.29682721157125924,
	"hoursXW=>45": 0.5931633305093778,
	"edu=Bachelors": 0.38229573518897564,
	"occup=Prof": 0.2789518075033849,
	"occup=White-Collar": 0.30882838462330076,
	"hoursXW=(40-45]": 0.2940327913687168,
	"workcl=Local-gov": 0.16767477382464813,
	"edu=Masters": 0.37074276132969974
}
```

**Comment by Sunt-ing** [comment]
I'll try to repro it in my Mac

**Comment by elianap** [comment]
I think the first are "output\dict\global_shapley_positive_fpr_top_normalized.json" but it does not change the fact that they do not precisely match..
Could you do me the favor of posting also the "not normalized" ones? It is named "global_shapley_positive_fpr_top.json"

I thank you for your availability, I cannot understand the source of this difference.

**Comment by Sunt-ing** [comment]
Sure. Here is it:
```json
{
	"sex=M": 0.0029965456035275957,
	"status=Married": 0.008191948301396556,
	"relation=Husband": 0.005848193294379629,
	"age=>47": 0.00208861404148524,
	"age=(37-47]": 0.002431593171639453,
	"hoursXW=>45": 0.004859163337817021,
	"edu=Bachelors": 0.0031317468985124766,
	"occup=Prof": 0.002285158785648853,
	"occup=White-Collar": 0.002529906160837891,
	"hoursXW=(40-45]": 0.0024087014258078474,
	"workcl=Local-gov": 0.001373583078619878,
	"edu=Masters": 0.0030371055339299025
}
```

**Comment by Sunt-ing** [comment]
Sure, here you are:

`output\dict\global_shapley_positive_fpr_top.json`:
```json
{
	"sex=M": 0.0029207111717683997,
	"status=Married": 0.009783320713675723,
	"relation=Husband": 0.005426862378197551,
	"age=>47": 0.0021992322593093055,
	"age=(37-47]": 0.0024372394560877846,
	"hoursXW=>45": 0.0064931342864382735,
	"edu=Bachelors": 0.0030974152502187043,
	"occup=Prof": 0.0022180221897824745,
	"occup=White-Collar": 0.0024664550321715265,
	"hoursXW=(40-45]": 0.0024087014258078474,
	"workcl=Local-gov": 0.001373583078619878,
	"edu=Masters": 0.0030371055339299025
}
```



`output\dict\individual_shapley_top.json`:
```json
{
	"sex=M": 0.03006035284364629,
	"status=Married": 0.12952770649763323,
	"relation=Husband": 0.12718718168155202,
	"age=>47": 0.048569684747958516,
	"age=(37-47]": 0.05432205635063282,
	"hoursXW=>45": 0.08705671062529717,
	"edu=Bachelors": 0.0839529753258141,
	"occup=Prof": 0.09117610167925443,
	"occup=White-Collar": 0.10526699276236422,
	"hoursXW=(40-45]": 0.05443030879533385,
	"workcl=Local-gov": 0.03443273257114886,
	"edu=Masters": 0.1515176334748451
}
```

**Comment by elianap** [comment]
Thank you. While the individual results corresponds, there is a slightly difference in the global results, here reported:
```
{'sex=M': 7.583443175919599e-05,
 'status=Married': -0.0015913724122791663,
 'relation=Husband': 0.00042133091618207826,
 'age=>47': -0.00011061821782406547,
 'age=(37-47]': -5.6462844483314185e-06,
 'hoursXW=>45': -0.001633970948621252,
 'edu=Bachelors': 3.4331648293772256e-05,
 'occup=Prof': 6.713659586637857e-05,
 'occup=White-Collar': 6.345112866636441e-05,
 'hoursXW=(40-45]': 0.0,
 'workcl=Local-gov': 0.0,
 'edu=Masters': 0.0}
```

However, other than the predicted labels (that are fixed for reproducibility purposes), I cannot derive the source of this slight difference (nor reproduce it in my three settings (the one reported in the reproducibility setting+ Mac OS&another Linux based system) 
Thank you again for your availability!

**Comment by Sunt-ing** [comment]
Good news:
- I repro the figure_9 in my Mac
<img width="400" alt="图片" src="https://user-images.githubusercontent.com/43040147/150182959-8a251c45-8cd7-42a6-a2d6-f7b4e13c0069.png">



Bad news:
- When installing `requirements.txt`, the error message occurred:
```
Traceback (most recent call last):
  File "run_experiments.py", line 68, in <module>
    show_figures=args.no_show_figs,
  File "/Users/sunt/code/divexplorer_SIGMOD21_experiments/E02_adult.py", line 478, in adult_experiments
    fig1.write_image(output_file_name, width=600, height=330)
  File "/usr/local/anaconda3/envs/divexplorer-exp/lib/python3.6/site-packages/plotly/basedatatypes.py", line 2824, in write_image
    return pio.write_image(self, *args, **kwargs)
  File "/usr/local/anaconda3/envs/divexplorer-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1767, in write_image
    fig, format=format, scale=scale, width=width, height=height, validate=validate
  File "/usr/local/anaconda3/envs/divexplorer-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1532, in to_image
    ensure_server()
  File "/usr/local/anaconda3/envs/divexplorer-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1390, in ensure_server
    validate_executable()
  File "/usr/local/anaconda3/envs/divexplorer-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1087, in validate_executable
    instructions=install_location_instructions,
ValueError:
The orca executable is required to export figures as static images,
but it could not be found on the system path.

Searched for executable 'orca' on the following path:
    /usr/local/anaconda3/envs/divexplorer-exp/bin
    /usr/local/anaconda3/condabin
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /Users/sunt/Library/Python/3.8/bin
    /Library/TeX/texbin
    /Users/sunt/.cargo/bin

If you haven't installed orca yet, you can do so using conda as follows:

    $ conda install -c plotly plotly-orca

Alternatively, see other installation methods in the orca project README at
https://github.com/plotly/orca

After installation is complete, no further configuration should be needed.

If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the `plotly.io.orca.config.executable`
property to the full path of your orca executable. For example:

    >>> plotly.io.orca.config.executable = '/path/to/orca'

After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

    >>> plotly.io.orca.config.save()

If you're still having trouble, feel free to ask for help on the forums at
https://community.plot.ly/c/api/python
```
After I run `conda install -c plotly plotly-orca`, and run `python run_experiments.py`, error occurs again:
```
Traceback (most recent call last):
  File "run_experiments.py", line 68, in <module>
    show_figures=args.no_show_figs,
  File "/Users/sunt/code/divexplorer_SIGMOD21_experiments/E02_adult.py", line 478, in adult_experiments
    fig1.write_image(output_file_name, width=600, height=330)
  File "/usr/local/anaconda3/envs/divexplorer-exp/lib/python3.6/site-packages/plotly/basedatatypes.py", line 2824, in write_image
    return pio.write_image(self, *args, **kwargs)
  File "/usr/local/anaconda3/envs/divexplorer-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1767, in write_image
    fig, format=format, scale=scale, width=width, height=height, validate=validate
  File "/usr/local/anaconda3/envs/divexplorer-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1676, in to_image
    raise ValueError(err_message)
ValueError:
The image request was rejected by the orca conversion utility
with the following error:
   503:
```
But figure_9 is outputted successfully.
<img width="166" alt="图片" src="https://user-images.githubusercontent.com/43040147/150183791-a3cfc492-c63f-456b-b846-a66acc5e38e3.png">
And it seems that the result is correct.

Another bad news, I built everything from scratch in my Windows, but nothing changed.

**Comment by Sunt-ing** [comment]
`python E02_adult.py --compute_results figure_9 --no_show_figs` can be run successfully on my Mac.

**Comment by Sunt-ing** [comment]
I will be available about 10 hours later. Good luck!

**Comment by elianap** [comment]
Thank you for all of your work!

So to recap:
-- Figure 9 was reproducible on Mac
-- Figure 9 is still not reproducible on Windows (sorry I really do not know why, something why the libraries I think..)
-- Mac OS and Orca (required for figure_11):
I tried too in a Mac OS (before I tried just Figure 9) and I get too the error message for requirement. I added in the requirement specification of the repository, thank you!
I run in the environment (as suggested): conda install -c plotly plotly-orca 
and I did not get the second error (The image request was rejected by the orca conversion utility with the following error: 503). I run it entirely (also on Mac).

**Comment by Sunt-ing** [comment]
> "I added in the requirement specification of the repository"

But nothing changed.

**Comment by Sunt-ing** [comment]
```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1559, in to_image
    figure=fig_dict, format=format, scale=scale, width=width, height=height
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1468, in request_image_with_retrying
    response = post(server_url + "/", data=json_str)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/adapters.py", line 413, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/adapters.py", line 310, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/adapters.py", line 190, in proxy_manager_for
    **proxy_kwargs
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/adapters.py", line 48, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_experiments.py", line 68, in <module>
    show_figures=args.no_show_figs,
  File "/Users/sunt/code/tmp/divexplorer_SIGMOD21_experiments/E02_adult.py", line 478, in adult_experiments
    fig1.write_image(output_file_name, width=600, height=330)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/basedatatypes.py", line 2824, in write_image
    return pio.write_image(self, *args, **kwargs)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1767, in write_image
    fig, format=format, scale=scale, width=width, height=height, validate=validate
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1591, in to_image
    info=status_str
ValueError:
For some reason plotly.py was unable to communicate with the
local orca server process, even though the server process seems to be running.

Please review the process and connection information below:

orca status
-----------
    state: running
    executable: /usr/local/anaconda3/envs/new-exp/bin/orca
    version: 1.3.1
    port: 57114
    pid: 95601
    command: ['/usr/local/anaconda3/envs/new-exp/bin/orca', 'serve', '-p', '57114', '--plotly', '/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/package_data/plotly.min.js', '--graph-only', '--mathjax', 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js']
```

**Comment by Sunt-ing** [comment]
Seems like something related to network got wrong. Maybe my network proxy? But after I turn off the proxy, the new error is:
```
(new-exp)  ✘ sunt@bogon  ~/code/tmp/divexplorer_SIGMOD21_experiments   main ±  python E02_adult.py --compute_results figure_11 --no_show_figs
Traceback (most recent call last):
  File "E02_adult.py", line 521, in <module>
    use_processed=args.retrain,
  File "E02_adult.py", line 478, in adult_experiments
    fig1.write_image(output_file_name, width=600, height=330)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/basedatatypes.py", line 2824, in write_image
    return pio.write_image(self, *args, **kwargs)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1767, in write_image
    fig, format=format, scale=scale, width=width, height=height, validate=validate
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1676, in to_image
    raise ValueError(err_message)
ValueError:
The image request was rejected by the orca conversion utility
with the following error:
   503:

(new-exp)  ✘ sunt@bogon  ~/code/tmp/divexplorer_SIGMOD21_experiments   main ±  python E02_adult.py --compute_results figure_11 --no_show_figs
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fad934ea780>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1087): Max retries exceeded with url: http://localhost:57646/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad934ea780>: Failed to establish a new connection: [Errno 61] Connection refused',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1559, in to_image
    figure=fig_dict, format=format, scale=scale, width=width, height=height
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1468, in request_image_with_retrying
    response = post(server_url + "/", data=json_str)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=1087): Max retries exceeded with url: http://localhost:57646/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad934ea780>: Failed to establish a new connection: [Errno 61] Connection refused',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E02_adult.py", line 521, in <module>
    use_processed=args.retrain,
  File "E02_adult.py", line 478, in adult_experiments
    fig1.write_image(output_file_name, width=600, height=330)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/basedatatypes.py", line 2824, in write_image
    return pio.write_image(self, *args, **kwargs)
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1767, in write_image
    fig, format=format, scale=scale, width=width, height=height, validate=validate
  File "/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/io/_orca.py", line 1591, in to_image
    info=status_str
ValueError:
For some reason plotly.py was unable to communicate with the
local orca server process, even though the server process seems to be running.

Please review the process and connection information below:

orca status
-----------
    state: running
    executable: /usr/local/anaconda3/envs/new-exp/bin/orca
    version: 1.3.1
    port: 57646
    pid: 96069
    command: ['/usr/local/anaconda3/envs/new-exp/bin/orca', 'serve', '-p', '57646', '--plotly', '/usr/local/anaconda3/envs/new-exp/lib/python3.6/site-packages/plotly/package_data/plotly.min.js', '--graph-only', '--mathjax', 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js']
```

**Comment by elianap** [comment]
Thank you! 
It is an orca issues. I use it to save figure_11. I find this issue in github: https://github.com/plotly/orca/issues/236
I tried to set the localhost port but it does not seem to work.

PS: I commit the requirement, thank you

**Comment by elianap** [comment]
I also find this:
https://github.com/plotly/orca/issues/240

I added the timeout as suggested.

Moreover a user report this issue for MACOS, I do not know if this is the case.

You can try running : python E02_adult.py --compute_results figure_11 --no_show_figs

**Comment by Sunt-ing** [comment]
After git pull and run `python E02_adult.py --compute_results figure_11 --no_show_figs`, my macOS cannot end the program while my Windows will finish the program quickly. Seems like a new problem.

**Comment by elianap** [comment]
I went back to the former version to avoid the problem you experience with macOS. 
I think it is a problem of configuration with the orca package. I just use it to save the result.
In my MacOS I do not experience this issue.

**Comment by elianap** [comment]
I could try to use Kaleido https://plotly.com/python/static-image-export/ but it requires to update plotly.

**Comment by elianap** [comment]
I modify to use kaleido rather than orca
I firstly updated plotly and installed kaleido (I also update the requirements)
```
pip install plotly==5.3.1
pip install kaleido
python E02_adult.py --compute_results figure_11 --no_show_figs
``` 

I hope there is no issue with Kaleido

**Comment by Sunt-ing** [comment]
I'm very happy to tell you that all the figures and tables have been reproduced in both Windows and macOS! Congratulations!

**Comment by Sunt-ing** [comment]
I will spend some time studying the compliance of the project. Thanks for your help!

**Comment by elianap** [comment]
Thank for all your work and availability! I can now (and finally) close this issue!

**Comment by elianap** [comment]
What the compliance of the project refer to? In case of any issues, feel free contact me!

**Comment by Sunt-ing** [comment]
Just to ensure that these results are obtained in a reasonable manner.
